[tools]
chezmoi = "latest"
node = "24"
python = "3.12"
lazygit = "latest"
gh = "latest"
yq = "latest"
atuin = "latest"
direnv = "latest"
delta = "latest"
jq = "latest"
neovim = "latest"
tree-sitter = "latest"
k9s = "latest"
kubectx = "latest"
kubens = "latest"
stern = "latest"
lazydocker = "latest"
tlrc = "latest"
yazi = "latest"
btop = "latest"
dust = "latest"
duf = "latest"
jless = "latest"

[settings]
lockfile = true
idiomatic_version_file_enable_tools = []
